### ISSUE TITLE
How to access admin site? - BUG

### ISSUE THREAD

**Issue by AndiLeni** [flextype-plugins/admin#1]
which is the correct url to access the admin site?

**Comment by koreos** [comment]
domain.com/admin/ - it works for me

**Comment by koreos** [comment]
but if you add any plugins you will see error 404 page

**Comment by leon9208** [comment]
> 
> 
> but if you add any plugins you will see error 404 page

http://flextype.org/download

Download  **lFlextype+admin**

**Comment by AndiLeni** [comment]
The link seems to be broken when flextype is not located in the documentroot.
Trying to open the admin site under XAMPP redirects to the documentroot.

**Comment by Awilum** [comment]
All plugins need to be updated for Fkextype 0.7.0 - I will do this ASAP

**Comment by Awilum** [comment]
Issue with url I will double check

**Comment by koreos** [comment]
> The link seems to be broken when flextype is not located in the documentroot.

Maybe this is a problem, I have Flextype in documentroot and it works.

**Comment by Awilum** [comment]
on my local dev Flextype with Admin plugin installed in different subfolders - works fine
@AndiLeni seems this server issue, check your .htaccess file 
`RewriteBase /your/sub-folders/here`

**Comment by AndiLeni** [comment]
Mhmm. I tried want you said, but it didn't work. I'm gonna have a deeper look at this later.

**Comment by AndiLeni** [comment]
I still can not access the admin panel with xampp. Even after modifying the .htaccess file

**Comment by Awilum** [comment]
@AndiLeni 
1. What do you see instead of Admin Panel ? 
2. Is any pages works ? did you try to create any page manually and test them ?
3. Did you check apache **error** and **access** logs ?

**Comment by AndiLeni** [comment]
@Awilum 
1. I get a 404 error page
2. the default page works fine. Nontheless I can't access any other page.
3. Yes, but there aren't any conspicuous entries.
4. The project is located on: [https://www.lenhardt.eu/flextype/](https://www.lenhardt.eu/flextype/)

**Comment by koreos** [comment]
Do you really have admin plugin? There is no index file https://www.lenhardt.eu/flextype/admin/

**Comment by Awilum** [comment]
@AndiLeni default page is not a new page. Please create new page in `pages` folder and check if it will  work

**Comment by Awilum** [comment]
> Do you really have admin plugin? There is no index file https://www.lenhardt.eu/flextype/admin/
yes, really server issue.

>  default page is not a new page. Please create a new page in pages folder and check if it will work

**Comment by AndiLeni** [comment]
As I already mentioned, I can't access any other page. This includes my created pages as well as the admin page. 
My server is runing on php 7.2.11, has mod_rewrite enabled and mb_string installed.
The .htaccess in the DocumentRoot contains the following lines:
````
RewriteEngine On

RewriteBase /flextype/

RewriteCond %{HTTPS} !=on
RewriteCond %{ENV:HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

RewriteCond %{HTTP_HOST} !=www.lenhardt.eu
RewriteRule (.*) http://www.lenhardt.eu/$1 [R=301,L]
````
(Removing the rest didnt't solve the problem)

**Comment by AndiLeni** [comment]
I finally had time to resolve the issue.
The documentation I had about apache config was probably wrong in that point. It said, I should put the RewriteBase in my documentroot, not in the subfolder. Obviously it belongs in the subfolders htaccess file.
