### ISSUE TITLE
UI broken on mobiles

### ISSUE THREAD

**Issue by AndiLeni** [flextype-plugins/admin#37]
The UI is broken on small screens.

Currently there is an issue with tables inside cards. This should be fixed with Bootstrap 4.2.
[https://github.com/twbs/bootstrap/pull/25193](https://github.com/twbs/bootstrap/pull/25193)

The navbar is missaligned, too. I took a quick look at it, but didn't have the time to create a pr by myself until now.

![screenshot_2018-11-25 flextype](https://user-images.githubusercontent.com/13385771/48983388-b424e680-f0ee-11e8-9aa1-880100c71ad3.png)

**Comment by Awilum** [comment]
Thanks for your bug report. Need to check and fix it

**Comment by Awilum** [comment]
Closed for now. 
Layout will be new in Admin 2.0.0
