### ISSUE TITLE
Page Editor: Content editor

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/admin#4]
Content editor must be implemented.

**Comment by AndiLeni** [comment]
Which editor do you intend to implement? 
I'd like to have tinymce as an option.

**Comment by koreos** [comment]
I also like TinyMCE but someone like CKeditor. 
But Tiny can be light and fast in basic option.
Maybe implement both and admin will decide which use..

**Comment by Awilum** [comment]
I need to check several of them and decide what editor will be better for Flextype
Maybe we will have several variants of editors with help of plugins

**Comment by koreos** [comment]
Everything what is good for Flextype is important. 
But very important is also what is good for people. Especially for ordinary people who are not webmasters. It should be easy, useful and simple. Then people will like and use Flextype a lot and Flextype will have sponsors and popular very quickly.
Also very importand thing today is SEO.
So, in my opinion TinyMCE is very good and I think this is not only my opinion..

**Comment by koreos** [comment]
Great!

**Comment by Awilum** [comment]
In the process of integration https://alex-d.github.io/Trumbowyg/
Trumbowyg looks very nice for me!

**Comment by Awilum** [comment]
Implemented
closed for now
