### ISSUE TITLE
Page Editor: Files previews

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/admin#5]
Add mini previews for image files in files manager.
Maybe layout should be changed to grids instead of table rows.

**Comment by Awilum** [comment]
Work in progress 

<img width="989" alt="2018-11-19 0 07 10" src="https://user-images.githubusercontent.com/477114/48678061-33666780-eb8f-11e8-81bd-b24baf8a2c6f.png">

**Comment by AndiLeni** [comment]
Is the file manager global, means all my uploaded images are selectable from all pages?
This would prevent multiple uploads of the same image to use them on more than one page.
